flowchart TD
    start -- coward --> coward1[Still thinking about it?] --> coward3[Go for it. What have you got to lose?] --> coward-choices
    
    start--> go-around-back-i[Good thinking.]
    --> go-around-back-ii[Only losers use the front door.]
    --> coward-choices

    coward-choices -- !coward --o continue0[On second thought...] -- coward --> coward0[Maybe *you're* a loser?] ---> coward[Yeah. Maybe.] --> coward2[Okay. You're still in front of the cafe.] --> return

    coward-choices -- coward --o continue2[A lot, probably.] --> coward4[Right. Okay, sure. It's your own time you're wasting, here.] --> return
    
    coward-choices --o continue1[Find the back of the cafe.]
    -- !coward --x go-around-back-iv["You walk down the street until you come to a narrow alley, down off the street between a tailor and a travel agent (both closed)."]
    --> go-around-back-v[You glance back along the empty street. What a gloomy, dreary, day.] --o go-down[Enter the alley.]
    --> go-around-back-vi[You descend into the canyon alley. Soon you're below street level, and the ground floor of the Cafe Halcyon hangs above you.]
    --> go-around-back-vii[There's a little metal door with a wire mesh screen that you can't quite see through. A lantern burns beside it. In the corner is an ill-contained pile of cafe detritus: cardboard boxes, empty tins, milk crates. The smell of rot down here is strong.] --> back-choices

    back-choices --o knock[Knock on the door.]
    -- knocked --x go-around-back-vii-i-i[You knock on the metal door. It makes a tinny, hollow sound.] --> go-around-back-vii-i-ii[For a second, you're terrified. What if someone actually answers? What would you say?] --> go-around-back-vii-i-iii[Luckily, nobody comes to the door.] --> back-choices
    
    back-choices -- !isLanternOut --o go-around-back-vii-ii[Put out the lantern.] 
    -- isLanternOut --x go-around-back-vii-ii-i[You flick the knob on the bottom of the lantern and the flame goes out. A little oil drips to the ground.] 
    --> go-around-back-vii-ii-ii[Look at you. You're so mischievous.] --> back-choices

    back-choices 
    -- !isTrashed --o go-around-back-vii-iii[Dig through the pile of trash.] 
    -- isTrashed --x go-around-back-vii-iii-i0[Let's see what you can find.] 
    --> go-around-back-vii-iii-i[You pick up one of the boxes in the pile of trash. *JALEPEÑOS & ANCHOS — TINNED — EXTRA LARGE * it says. The J in *jalepeño* is a wiry little cartoon pepper, with big eyes and a wide grid.]
    --> go-around-back-vii-iii-ii[You brush aside more boxes, cans, egg cartons. There's half a stack of flour, gone moldy.]
    --o go-around-back-vii-iii-ii-i[Kick it over.]
    --> go-around-back-vii-iii-ii-i-i[Underneath, you find a box of toothpicks, unopened. Score! You put them in your pocket.]
    --> go-around-back-vii-iii-ii-i-ii[What other treasures can you find in this garden of leftovers?]

    %% kick cans
    go-around-back-vii-iii-ii-i-ii --o go-around-back-vii-iii-ii-i-ii-i[Kick the pile of cans.] --> go-around-back-vii-iii-ii-i-ii-i-i[There's a tempting heap of cans like billiard balls beside the door.] --> go-around-back-vii-iii-ii-i-ii-i-ii[You step back, gauge the angle, and run at them. As you swing your leg to kick, you step on a patch of grease and tumble forward into the heap of boxes.] --> go-around-back-vii-iii-ii-i-ii-i-iii[When the mold spores settle, you're laying on a bed of cardboard and banana peels. It's surprisingly warm.] --> go-around-back-vii-iii-ii-i-iii1

    %% climb in box
    go-around-back-vii-iii-ii-i-ii --o go-around-back-vii-iii-ii-i-ii-ii[Climb into the biggest box.] --> go-around-back-vii-iii-ii-i-ii-ii-i[At the bottom of the pile is the mother of all boxes. It's wide. It's long. It's spotted like a dog from mildew and rain. It's calling to you.] --> go-around-back-vii-iii-ii-i-ii-ii-ii[You sweep the majority of the tins from the box and climb inside. It's long enough for you to stretch out, and you lower yourself until you're entirely under the lip of the box. It's surprisingly comfy.] --> go-around-back-vii-iii-ii-i-iii1
    
    go-around-back-vii-iii-ii-i-iii1[*You could lie here all day,* says a part of you that you wish would shut up.] --> go-around-back-vii-iii-ii-i-iii[Suddenly, you feel something move beneath you.]
    
    %% exclaimations against wriggling
    go-around-back-vii-iii-ii-i-iii --o go-around-back-iii-ii-i-iii-i[Aaugh!] --> go-around-back-iii-ii-i-iv
    go-around-back-vii-iii-ii-i-iii --o go-around-back-iii-ii-i-iii-ii[Yee-ow!] --> go-around-back-iii-ii-i-iv
    go-around-back-vii-iii-ii-i-iii --o go-around-back-iii-ii-i-iii-iii[Ahooga!] --> go-around-back-iii-ii-i-iv
    
    %% croissant reveal
    go-around-back-iii-ii-i-iv[You twist, reach down. Something wriggles against your arm.] 
    --> go-around-back-iii-ii-i-v[You see a tail disappear under a box. There's a scraping sound, something shifts.] 
    --> go-around-back-iii-ii-i-vi[And then: a rat! It's found half a croissant, somewhere in the pile, and it's dragging it towards the storm drain.] 
    
    go-around-back-iii-ii-i-vi --o go-around-back-iii-ii-i-vii[Grab the croissant!] 
    --> go-around-back-iii-ii-i-viii[Like a raccoon, desperate and hungry, you leap up and snatch the croissant from the feeble grasp of the little rat.] --> go-around-back-iii-ii-i-ix

    go-around-back-iii-ii-i-vi --o go-around-back-iii-ii-iivii2[Grab the rat!]
    --> go-around-back-iii-ii-i-vii2[Like Goya's Saturn, you snatch the rat. Your fingers press into its fleshy underbelly. You are meat against meat.]
    --> go-around-back-iii-ii-i-vii3[The rat stratches and bites at your knuckles and nails. Its beady eyes are frantic.]
    
    go-around-back-iii-ii-i-vii3 --o go-around-back-iii-ii-i-vii4[Let it go.] 
    --> go-around-back-iii-ii-i-vii6[You drop the rat, and it scurries under a can.] 
    --> go-around-back-iii-ii-i-vii8
    
    go-around-back-iii-ii-i-vii3 --o go-around-back-iii-ii-i-vii5[Squeeze harder.] 
    --> go-around-back-iii-ii-i-vii7[You show no mercy. The rat squeals. And then, like an eel, it wriggles free. You watch it scurry under a can.] 
    --> go-around-back-iii-ii-i-vii8

    go-around-back-iii-ii-i-vii8[The croissant, however, is still within reach.]--o go-around-back-iii-ii-i-vii9[Pick up the croissant.] --> go-around-back-iii-ii-i-ix

    %% contemplate the croissant
    go-around-back-iii-ii-i-ix[Rainwater drips out the end of the croissant as you raise it to your lips. It's fluffy, flaky, sumptuous. Sure, it's a little flat, and a little cold, but you've never wanted anything so much in your life.] 
    --> go-around-back-iii-ii-i-x[The rat stares up at you. There is wonder in its eyes. You are its god, tall and terrible.] 
    --> go-around-back-iii-ii-i-xi-b[You're only staring at the beautiful croissant. It looks delicious.]
    
    %% illusion of choice
    go-around-back-iii-ii-i-xi-b --o go-around-back-iii-ii-i-viii-i[Take a bite.] --> go-around-back-iii-ii-i-xii
    go-around-back-iii-ii-i-xi-b --o go-around-back-iii-ii-i-viii-ii[Resist the croissant.] --> go-around-back-iii-ii-i-viii-iii[You try to resist, but it looks so tasty.] --o go-around-back-iii-ii-i-viii-iv[Take a bite.] --> go-around-back-iii-ii-i-xii

    go-around-back-iii-ii-i-xii[You take a bite, chew. There's a pain in your chest.] --o go-around-back-iii-ii-i-xii2[Take another bite.] -- ate-croissant --> go-around-back-iii-ii-i-xiii[It's disgusting, of course. You spit it out. The rat breaks from its stupor and darts down the drain.] --> go-around-back-iii-ii-i-xiv[What's gotten into you? You drop the croissant and try your best to kick the mess of garbage back into a pile. Hopefully nobody will notice.] --> back-choices
    
    %% no toothpicks for you
    go-around-back-vii-iii-ii --o go-around-back-vii-iii-ii-ii[Leave it.] --x go-around-back-vii-iii-ii-iii[That's probably wise.] --> back-choices

    %% leave alley
    back-choices --o go-around-back-vii-iv[Leave the alley.] --x go-around-back-vii-iv-i[Why'd you come down here, anyway?] --> go-around-back-vii-iv-ii[You leave the alley and return to the front of the cafe.] --> return