flowchart TD

    start --> a[
        The door bangs shut behind you.
        For a second, you think the glass has broken,
        but it seems like it just makes that noise every time.
    ] --> enter-choices

    enter-choices --o a1[Look around.] --> b
    enter-choices --o a2[Approach the counter.] --> fish_convo.mmd

    b[There are only a few tables, and they're all occupied.]
    
    b --> |morning-start-outside:wavedAtOldMan| ba[
        The old man in the window looks up.
        He smiles at you.
    ] --> c

    b --> |morning-start-outside:ignoredOldMan| bb[
        The old man in the window looks up at you,
        his eyebrows raised.
    ] --> c

    b --> bb[
        To your right, beside the window, an old man is reading.
    ] --> c

    c[To your left, a gaggle of children hold court over a long table.]
    --> d[
        And in front of you is a wide glass counter,
        where two women are talking.
        One of them seems to be the proprietor of the place.
    ] --> enter-choices

    fish_convo.mmd --> fc[Hmm. What _can_ she get for you?] --> ordering-choices

    ordering-choices --o o1[Look around.] -- looked-around --> look-around[You look around. Aside from an enamel bowl of tomatoes, and a few loose tortillas, you don't see any food.] --> ordering-choices
    ordering-choices -- ! --o o2[What do you have?] -- asked--> ask-her[''Well, we've got all sorts of things, I suppose. What are you in the mood for?''] --> ordering-choices
    ordering-choices -- ! --o o3[''One pig liver sandwich, please!''] --> liver[''Wow, you're enthusiastic. I don't think we have any of those.''] --> ordering-choices
    ordering-choices -- asked --o o4[Ask for the special.] --> special
    ordering-choices -- looked-around --o o5[Tomato tortilla?] --> tom-tot[You point at the counter and ask for some tomatoes in a tortilla.] --> tom-tot2[She smiles.] --> tom-tot3[''Oh, sure. I guess I can do that.'']
    ordering-choices -- asked --o o6[Coffee and a cigraette.] --> french-breakfast[''Ah, you're one of them,'' she says knowingly.] --> fb2[You're a little early. Most of the poets don't normally arrive until noon. But I think Parnassus is here.''] --o fb3[''Parnassus?''] --> fb4[''Parnassus. One of the poets. He's in the other room.'']
    ordering-choices -- fish_convo:listened --o o7[Did you save any of those fish?] --> fish[''Oh! Um.''] --> fish2[She's a little taken aback. Maybe she didn't realize you'd heard all that.] --> fish3[''No. I made him put them all back in the sea.''] --> ordering-choices


    %% once you've ordered, you have to choose where to sit.
    %% and I have to make it really easy to go take your food outside and be alone.
    %% but difficult/rewarding to sit down with some rando