flowchart TD
    i[Here it is. You've *arrived*.]
    --> ii[
        You're standing on the street, staring at the door.
        You hear clinking mugs and smell fresh bread.
    ]
    --> iii[
        It's been a long time coming, but here you are.
        *Cafe Halcyon*. Time to see what all the fuss is about.
    ]
    iii --> base-choices
    
    %% hub
    base-choices --o go-inside(Go inside.) --x inside[morning-ordering.mmd]
    base-choices --o check-hours(Check the hours.)
    base-choices --o investigate-feelings[Introspect.]
    base-choices -- ! --o peer-through-glass(Peer through the glass.)
    base-choices --o go-around-back(Go around back.) --x around-back[around-back.mmd] --> base-choices
    base-choices --o leave(Leave.)

    %% 
    %% hours
    %% 

    check-hours 
    --> check-hours-i[There's a sign on the door. It reads:]
    ---> mon[
        Monday:
        07.30-23.00.
    ]
    --> tues[
        Tuesday:
        07.30-23.00.
    ]
    --> wed[
        Wednesday:
        07.30-23.00.
    ]
    --> thurs[
        Thursday:
        07.30-23.00.
    ]
    --> fri[
        Friday:
        07.30-02.00.
    ]
    --> sat[
        Saturday:
        07.30-02.00.
    ]
    --> sun[
        Sunday:
        07.30-23.00.
    ]
    ----> check-hours-iii[
        Well,
        yep.
        They're open.
    ]
    --> base-choices

    %% 
    %% investigate your feelings
    %% 

    investigate-feelings --> if1[You reach inward.]
    --> if2[Why are you here?]
    ---> if6[You know very well why you're here.]
    --> if3[You've passed this door hundreds, thousands of times.]
    --> if4[It always seemed like the kind of place you'd go.]
    --> if5[Or the kind of place the person you think you are would go.]
    --> if9[But you've never gone inside.]
    ---> if8[Will today be any different?]
    --> base-choices

    %% 
    %% peer through glass
    %% 

    peer-through-glass --> peer-through-glass-i[You approach the window beside the door and peer through it, brushing aside the fronds of a rosemary plant. The window is wet from dew and last night's rain.]
    --> peer-through-glass-ii[You get closer, but you can't see inside.]

    %% don't wipe glass
    peer-through-glass-ii 
    --o peer-through-glass-ii-i(1\. Step away.)
    --> base-choices

    %% surprise! old man
    peer-through-glass-ii --o peer-through-glass-ii-ii(2\. Wipe off the condensation.) 
    --> peer-through-glass-iii[You wipe the **condensation** from the glass, and it soaks into your sleeve, heavy and cold against your wrist.]
    --> peer-through-glass-iv[You look back at the window and jump. There's an old man on the other side of the window, staring back at you!]
    --> peer-through-glass-v[His eyebrows are bushy and his eyes are beady. Magnified by the warp of the glass, he looks like a fish in a tank.]

    %% ignore him
    peer-through-glass-v --o peer-through-glass-v-i(1\. Pretend you don't see him.) 
    -- ignoredOldMan --> peer-through-glass-v-i-i[You quickly turn away.] 
    --> base-choices

    %% wave at him
    peer-through-glass-v --o peer-through-glass-v-ii(2\. Wave to him.) 
    -- wavedAtOldMan --> peer-through-glass-v-ii-i[His nose wrinkles as he smiles back at you.] 
    --> base-choices
    
    %% 
    %% leave
    %% 

    leave --> leave-i[You turn around.]
    --> leave-ii[It was a silly idea, anyway. To think you'd just walk inside and start your life.]
    --> leave-iii[Oh well. There's always tomorrow.]
    --> reset